--Problem 1
CREATE TABLE [Passports](
[PassportID] INT PRIMARY KEY IDENTITY(101,1),
[PassportNumber] NVARCHAR(40) NOT NULL
)

CREATE TABLE [Persons](
[PersonID] INT PRIMARY KEY IDENTITY(101,1),
[FirstName] NVARCHAR(40) NOT NULL,
[Salary] DECIMAL(8,2) NOT NULL,
[PassportID] INT FOREIGN KEY REFERENCES Passports([PassportID]) UNIQUE 
)

--Problem 2
CREATE TABLE [Manufacturers](
[ManufacturerID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[EstablishedOn] DATE NOT NULL
)

CREATE TABLE [Models](
[ModelID] INT PRIMARY KEY IDENTITY(101,1),
[Name] NVARCHAR(50) NOT NULL,
[ManufacturerID] INT FOREIGN KEY REFERENCES Manufacturers([ManufacturerID])
)

--Problem 3
CREATE TABLE [Students](
[StudentID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
)
CREATE TABLE [Exams](
[ExamID] INT PRIMARY KEY IDENTITY(101,1),
[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE [StudentsExams](
[StudentID] INT FOREIGN KEY REFERENCES Students([StudentID]) NOT NULL,
[ExamID] INT FOREIGN KEY REFERENCES Exams([ExamID]) NOT NULL,
PRIMARY KEY([StudentID],[ExamID])
)

--Problem 4
CREATE TABLE [Teachers](
[TeacherID] INT PRIMARY KEY IDENTITY (101,1),
[Name] NVARCHAR(50) NOT NULL,
[ManagerID] INT FOREIGN KEY REFERENCES Teachers([TeacherID])
)



INSERT INTO Teachers([Name],[ManagerID])
     VALUES ('John',NULL),
	        ('Maya',106),
			('Silvia',106),
			('Ted',105),
		    ('Mark',101),
			('Greata',101)


--Problem 5
CREATE TABLE [Cities](
[CityID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
)


CREATE TABLE [ItemTypes](
[ItemTypesID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE [Items](
[ItemID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[ItemTypeID] INT FOREIGN KEY REFERENCES ItemTypes([ItemTypesID])
)


CREATE TABLE [Customers](
[CustomerID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[Birthday] DATE NOT NULL,
[CityID] INT FOREIGN KEY REFERENCES Cities([CityID])
)

CREATE TABLE [Orders](
[OrderID] INT PRIMARY KEY IDENTITY,
[CustomerID] INT FOREIGN KEY REFERENCES Customers([CustomerID])
)

CREATE TABLE [OrderItems](
[OrderID] INT FOREIGN KEY REFERENCES Orders([OrderID]),
[ItemID] INT FOREIGN KEY REFERENCES Items([ItemID])
PRIMARY KEY([OrderID],[ItemID])
)



